# Generated by Django 3.1.2 on 2020-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEN', models.CharField(max_length=100)),
                ('addressEN', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
