# Generated by Django 3.1.2 on 2020-10-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visited_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='addressEN',
            new_name='VisitedLocAddressEN',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='category',
            new_name='VisitedLocCategory',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='date_from',
            new_name='VisitedLocDateFrom',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='date_to',
            new_name='VisitedLocDateTo',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='nameEN',
            new_name='VisitedLocNameEN',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='x',
            new_name='VisitedLocX',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='y',
            new_name='VisitedLocY',
        ),
    ]
