# Generated by Django 3.1.2 on 2020-10-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visited_location', '0002_auto_20201024_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocAddressEN',
            new_name='visitedLocAddressEN',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocCategory',
            new_name='visitedLocCategory',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocDateFrom',
            new_name='visitedLocDateFrom',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocDateTo',
            new_name='visitedLocDateTo',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocNameEN',
            new_name='visitedLocNameEN',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocX',
            new_name='visitedLocX',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='VisitedLocY',
            new_name='visitedLocY',
        ),
    ]
