# Generated by Django 3.1.2 on 2020-10-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visited_location', '0005_auto_20201025_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedlocationrecord',
            name='visitedLoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visited_location.location'),
        ),
    ]
