# Generated by Django 3.1.2 on 2020-10-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visited_location', '0006_visitedlocationrecord_visitedloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locAddressEN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
