# Generated by Django 3.1.2 on 2020-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='virusBDay',
            field=models.IntegerField(),
        ),
    ]
