# Generated by Django 3.1.2 on 2020-10-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0002_auto_20201024_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virus',
            old_name='virusBDay',
            new_name='virusDay',
        ),
    ]
