# Generated by Django 3.1.2 on 2020-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0003_auto_20201024_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virus',
            name='id',
        ),
        migrations.AlterField(
            model_name='virus',
            name='virusName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
