# Generated by Django 3.1.2 on 2020-10-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientHKID', models.CharField(max_length=100)),
                ('patientBDay', models.DateField()),
            ],
        ),
    ]
