# Generated by Django 3.1.2 on 2020-10-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitedLocation',
            new_name='Patient',
        ),
    ]
