# Generated by Django 3.1.2 on 2020-10-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_auto_20201024_1227'),
        ('virus', '0003_auto_20201024_1251'),
        ('visited_location', '0003_auto_20201024_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('virus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virus.virus')),
                ('visitedLoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visited_location.visitedlocation')),
            ],
        ),
    ]
