# Generated by Django 3.1.2 on 2020-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caserecord',
            name='visitedLoc',
        ),
    ]
