# Generated by Django 3.1.2 on 2020-10-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0003_auto_20201024_1251'),
        ('patient', '0003_auto_20201024_1227'),
        ('case_record', '0002_remove_caserecord_visitedloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virus.virus'),
        ),
    ]
