# Generated by Django 3.1.2 on 2020-10-26 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_record', '0003_auto_20201024_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='caseDateofConfirm',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caserecord',
            name='caseType',
            field=models.CharField(default='local', max_length=50),
            preserve_default=False,
        ),
    ]
