# Generated by Django 3.1.2 on 2020-10-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0004_auto_20201026_1539'),
        ('case_record', '0004_auto_20201026_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virus', to='virus.virus'),
        ),
    ]
